//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart1
    {
        public string Ma { get; set; }
        public int ID { get; set; }
        public int SL { get; set; }
    
        public virtual PhanLoaiSach PhanLoaiSach { get; set; }
        public virtual PhanLoaiSach PhanLoaiSach1 { get; set; }
        public virtual PhanLoaiSach PhanLoaiSach2 { get; set; }
    }
}
