//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDemo.Models
{
    using System;
    using System.Collections.Generic;
	using System.Data.SqlClient;
	using System.Linq;

	public partial class User
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<int> Access { get; set; }
        public Nullable<bool> Statuss { get; set; }
        public string passwordd { get; set; }
        public string Fullname { get; set; }
        public Nullable<bool> IsHost { get; set; }
        public string UserGroupID { get; set; }
        public string GroupPermissions { get; set; }
    
        public virtual UsersGroup UsersGroup { get; set; }
  //      public UsersGroup GetObject_UserGroup(string groupid)
		//{
  //          return 
		//}
        public int Canxxi(string fullName, string acc, string password)
		{
            DemoMVCEntities1 haha = new DemoMVCEntities1();
            object[] parms =
                {
                    new SqlParameter("@fullName",fullName),
                    new SqlParameter("@acc",acc),
                    new SqlParameter("@pass",password)
                    };
            var res = haha.Database.ExecuteSqlCommand("Registeruser @fullName,@acc,@pass", parms);
            return res;



        }
        
    }
}
